# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arslan Rafique - Software - Web - Strategy - Mobile - Branding
email: maintoarslanATGMAIL
description: > # this means to ignore newlines until "baseurl:"
  Arslan is a Software Engineer with great experience in user centric software
  development and design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arslanrafique.github.io" # the base hostname & protocol for your site
twitter_username: arslan_rafique
github_username:  ArslanRafiqe

# Build settings
markdown: kramdown
theme: minima
